import pickle
import os

def create_sample_metadata():
    """
    This helper script creates a sample essential/transformer_metadata.pkl 
    matching the parameters from your training notebook.
    """
    
    # Dummy Vocab (User should replace with actual vocab from notebook)
    en_vocab = {"<unk>": 0, "<pad>": 1, "<sos>": 2, "<eos>": 3, "a": 4, "small": 5, "dog": 6}
    de_vocab = {"<unk>": 0, "<pad>": 1, "<sos>": 2, "<eos>": 3, "ein": 4, "kleiner": 5, "hund": 6}
    de_itos = {v: k for k, v in de_vocab.items()}

    deployment_package = {
        "en_vocab": en_vocab,
        "de_vocab": de_vocab,
        "de_itos": de_itos,
        "d_k": 128,          # From notebook
        "heads": 4,          # From notebook
        "head_dim": 32,      # From notebook
        "max_length": 128,   # From notebook
        "pad_index": 1       # From notebook
    }

    os.makedirs('essential', exist_ok=True)
    with open('essential/transformer_metadata.pkl', 'wb') as f:
        pickle.dump(deployment_package, f)

    print("✅ Metadata saved to essential/transformer_metadata.pkl")
    print("⚠️  Warning: These are DUMMY vocabularies. For real translations, use the .pkl generated by your notebook.")

if __name__ == "__main__":
    create_sample_metadata()
